services:
  phantombot:
    container_name: phantombot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_VERSION: "1.0"
    ports:
      - "25000:25000"
    restart: unless-stopped
    volumes:
      - PhantomBot_data:/opt/PhantomBot_data
    #
    # ------ Set any botlogin.txt variable here, with the PHANTOMBOT_ prefix
    # ------ Note that after first run, botlogin.txt takes priority
    # ------ None of the variables are required
    # ------ Uncomment the following line, then add your variables below it
    # ------ Remember to indent 2 spaces
    #environment:
      # If you uncomment this variable, your ENV variables will always override botlogin.txt
      # PHANTOMBOT_ENVOVERRIDE: true
volumes:
  PhantomBot_data:
